[project]
name = "stark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "sqlalchemy>=2.0.43",
    "streamlit>=1.48.1",
]
